services:
  python_dev:
    build: .
    volumes:
      - ./src/project:/app/src/project
    command: python
    stdin_open: true       # equivalent to -i (interactive)
    tty: true              # equivalent to -t (pseudo-TTY)
